### ISSUE TITLE
generateCircleMesh bug

### ISSUE THREAD

**Issue by MBakels** [rktrlng/rt2d#16]
I have noticed a bug in your generateCircleMesh function in the Mesh class.
When generating a circle with a certain number of segments the circle is incomplete.
This can be fixed by changing the int on line 102 in the Mesh class to a float,
(old) int deg = 360;
(new) float deg = 360;
and on line 121
(old) deg -= 360/step;
(new) deg -= 360.0f/step;

**Comment by rktrlng** [comment]
Well spotted, thanks!
The same bug was in generateSegmentMesh(). That's fixed now too.
https://github.com/rktrlng/rt2d/commit/d3d6d50c850f2c553185c7a8031c7023a061a32d
